# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: restaurant.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='restaurant.proto',
  package='RestaurantOrderSys',
  syntax='proto3',
  serialized_pb=_b('\n\x10restaurant.proto\x12\x12RestaurantOrderSys\"T\n\nRestaurant\x12\n\n\x02id\x18\x01 \x01(\r\x12\x0c\n\x04name\x18\x02 \x01(\t\x12,\n\x07\x61\x64\x64ress\x18\x03 \x01(\x0b\x32\x1b.RestaurantOrderSys.Address\")\n\x07\x41\x64\x64ress\x12\x10\n\x08location\x18\x01 \x01(\r\x12\x0c\n\x04name\x18\x02 \x01(\t\"T\n\x05Order\x12\n\n\x02id\x18\x01 \x01(\r\x12\x0e\n\x06sku_id\x18\x02 \x01(\r\x12/\n\x06status\x18\x03 \x01(\x0e\x32\x1f.RestaurantOrderSys.OrderStatus\"?\n\x0cOrderStatusD\x12/\n\x06status\x18\x01 \x01(\x0e\x32\x1f.RestaurantOrderSys.OrderStatus\"P\n\x06\x63ustom\x12\n\n\x02id\x18\x01 \x01(\r\x12\x0c\n\x04name\x18\x02 \x01(\t\x12,\n\x07\x61\x64\x64ress\x18\x03 \x01(\x0b\x32\x1b.RestaurantOrderSys.Address\">\n\x0ePlaceOrderResp\x12,\n\x03res\x18\x01 \x01(\x0e\x32\x1f.RestaurantOrderSys.OrderStatus\"#\n\x0fGetOrderListReq\x12\x10\n\x08orderIds\x18\x01 \x03(\r*&\n\x0bOrderStatus\x12\x0b\n\x07SUCCEED\x10\x00\x12\n\n\x06\x43\x41NCEL\x10\x01\x32\xd5\x02\n\x12RestaurantOrderSys\x12R\n\x0cGetOrderList\x12#.RestaurantOrderSys.GetOrderListReq\x1a\x19.RestaurantOrderSys.Order\"\x00\x30\x01\x12M\n\nPlaceOrder\x12\x19.RestaurantOrderSys.Order\x1a\".RestaurantOrderSys.PlaceOrderResp\"\x00\x12N\n\x0b\x43\x61ncelOrder\x12\x19.RestaurantOrderSys.Order\x1a\".RestaurantOrderSys.PlaceOrderResp\"\x00\x12L\n\x08GetOrder\x12#.RestaurantOrderSys.GetOrderListReq\x1a\x19.RestaurantOrderSys.Order\"\x00\x62\x06proto3')
)

_ORDERSTATUS = _descriptor.EnumDescriptor(
  name='OrderStatus',
  full_name='RestaurantOrderSys.OrderStatus',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='SUCCEED', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CANCEL', index=1, number=1,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=503,
  serialized_end=541,
)
_sym_db.RegisterEnumDescriptor(_ORDERSTATUS)

OrderStatus = enum_type_wrapper.EnumTypeWrapper(_ORDERSTATUS)
SUCCEED = 0
CANCEL = 1



_RESTAURANT = _descriptor.Descriptor(
  name='Restaurant',
  full_name='RestaurantOrderSys.Restaurant',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='RestaurantOrderSys.Restaurant.id', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='name', full_name='RestaurantOrderSys.Restaurant.name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='address', full_name='RestaurantOrderSys.Restaurant.address', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=40,
  serialized_end=124,
)


_ADDRESS = _descriptor.Descriptor(
  name='Address',
  full_name='RestaurantOrderSys.Address',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='location', full_name='RestaurantOrderSys.Address.location', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='name', full_name='RestaurantOrderSys.Address.name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=126,
  serialized_end=167,
)


_ORDER = _descriptor.Descriptor(
  name='Order',
  full_name='RestaurantOrderSys.Order',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='RestaurantOrderSys.Order.id', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='sku_id', full_name='RestaurantOrderSys.Order.sku_id', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='status', full_name='RestaurantOrderSys.Order.status', index=2,
      number=3, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=169,
  serialized_end=253,
)


_ORDERSTATUSD = _descriptor.Descriptor(
  name='OrderStatusD',
  full_name='RestaurantOrderSys.OrderStatusD',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='status', full_name='RestaurantOrderSys.OrderStatusD.status', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=255,
  serialized_end=318,
)


_CUSTOM = _descriptor.Descriptor(
  name='custom',
  full_name='RestaurantOrderSys.custom',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='RestaurantOrderSys.custom.id', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='name', full_name='RestaurantOrderSys.custom.name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='address', full_name='RestaurantOrderSys.custom.address', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=320,
  serialized_end=400,
)


_PLACEORDERRESP = _descriptor.Descriptor(
  name='PlaceOrderResp',
  full_name='RestaurantOrderSys.PlaceOrderResp',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='res', full_name='RestaurantOrderSys.PlaceOrderResp.res', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=402,
  serialized_end=464,
)


_GETORDERLISTREQ = _descriptor.Descriptor(
  name='GetOrderListReq',
  full_name='RestaurantOrderSys.GetOrderListReq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='orderIds', full_name='RestaurantOrderSys.GetOrderListReq.orderIds', index=0,
      number=1, type=13, cpp_type=3, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=466,
  serialized_end=501,
)

_RESTAURANT.fields_by_name['address'].message_type = _ADDRESS
_ORDER.fields_by_name['status'].enum_type = _ORDERSTATUS
_ORDERSTATUSD.fields_by_name['status'].enum_type = _ORDERSTATUS
_CUSTOM.fields_by_name['address'].message_type = _ADDRESS
_PLACEORDERRESP.fields_by_name['res'].enum_type = _ORDERSTATUS
DESCRIPTOR.message_types_by_name['Restaurant'] = _RESTAURANT
DESCRIPTOR.message_types_by_name['Address'] = _ADDRESS
DESCRIPTOR.message_types_by_name['Order'] = _ORDER
DESCRIPTOR.message_types_by_name['OrderStatusD'] = _ORDERSTATUSD
DESCRIPTOR.message_types_by_name['custom'] = _CUSTOM
DESCRIPTOR.message_types_by_name['PlaceOrderResp'] = _PLACEORDERRESP
DESCRIPTOR.message_types_by_name['GetOrderListReq'] = _GETORDERLISTREQ
DESCRIPTOR.enum_types_by_name['OrderStatus'] = _ORDERSTATUS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Restaurant = _reflection.GeneratedProtocolMessageType('Restaurant', (_message.Message,), dict(
  DESCRIPTOR = _RESTAURANT,
  __module__ = 'restaurant_pb2'
  # @@protoc_insertion_point(class_scope:RestaurantOrderSys.Restaurant)
  ))
_sym_db.RegisterMessage(Restaurant)

Address = _reflection.GeneratedProtocolMessageType('Address', (_message.Message,), dict(
  DESCRIPTOR = _ADDRESS,
  __module__ = 'restaurant_pb2'
  # @@protoc_insertion_point(class_scope:RestaurantOrderSys.Address)
  ))
_sym_db.RegisterMessage(Address)

Order = _reflection.GeneratedProtocolMessageType('Order', (_message.Message,), dict(
  DESCRIPTOR = _ORDER,
  __module__ = 'restaurant_pb2'
  # @@protoc_insertion_point(class_scope:RestaurantOrderSys.Order)
  ))
_sym_db.RegisterMessage(Order)

OrderStatusD = _reflection.GeneratedProtocolMessageType('OrderStatusD', (_message.Message,), dict(
  DESCRIPTOR = _ORDERSTATUSD,
  __module__ = 'restaurant_pb2'
  # @@protoc_insertion_point(class_scope:RestaurantOrderSys.OrderStatusD)
  ))
_sym_db.RegisterMessage(OrderStatusD)

custom = _reflection.GeneratedProtocolMessageType('custom', (_message.Message,), dict(
  DESCRIPTOR = _CUSTOM,
  __module__ = 'restaurant_pb2'
  # @@protoc_insertion_point(class_scope:RestaurantOrderSys.custom)
  ))
_sym_db.RegisterMessage(custom)

PlaceOrderResp = _reflection.GeneratedProtocolMessageType('PlaceOrderResp', (_message.Message,), dict(
  DESCRIPTOR = _PLACEORDERRESP,
  __module__ = 'restaurant_pb2'
  # @@protoc_insertion_point(class_scope:RestaurantOrderSys.PlaceOrderResp)
  ))
_sym_db.RegisterMessage(PlaceOrderResp)

GetOrderListReq = _reflection.GeneratedProtocolMessageType('GetOrderListReq', (_message.Message,), dict(
  DESCRIPTOR = _GETORDERLISTREQ,
  __module__ = 'restaurant_pb2'
  # @@protoc_insertion_point(class_scope:RestaurantOrderSys.GetOrderListReq)
  ))
_sym_db.RegisterMessage(GetOrderListReq)



_RESTAURANTORDERSYS = _descriptor.ServiceDescriptor(
  name='RestaurantOrderSys',
  full_name='RestaurantOrderSys.RestaurantOrderSys',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=544,
  serialized_end=885,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetOrderList',
    full_name='RestaurantOrderSys.RestaurantOrderSys.GetOrderList',
    index=0,
    containing_service=None,
    input_type=_GETORDERLISTREQ,
    output_type=_ORDER,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='PlaceOrder',
    full_name='RestaurantOrderSys.RestaurantOrderSys.PlaceOrder',
    index=1,
    containing_service=None,
    input_type=_ORDER,
    output_type=_PLACEORDERRESP,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='CancelOrder',
    full_name='RestaurantOrderSys.RestaurantOrderSys.CancelOrder',
    index=2,
    containing_service=None,
    input_type=_ORDER,
    output_type=_PLACEORDERRESP,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='GetOrder',
    full_name='RestaurantOrderSys.RestaurantOrderSys.GetOrder',
    index=3,
    containing_service=None,
    input_type=_GETORDERLISTREQ,
    output_type=_ORDER,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_RESTAURANTORDERSYS)

DESCRIPTOR.services_by_name['RestaurantOrderSys'] = _RESTAURANTORDERSYS

# @@protoc_insertion_point(module_scope)
